version: "3.8"

services:
  vulnerable-web:
    image: nginx:alpine
    container_name: vulnerable-web
    user: "nginx"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backup:/var/backups:rw
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  debug-shell:
    image: alpine:latest
    container_name: debug-shell
    # НЕ публикуем SSH наружу. Для отладки: docker exec -it debug-shell sh
    command: ["sh", "-c", "sleep infinity"]
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
